# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme             : "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Jacob R. Campbell, ..."
title_separator          : "-"
name                     : "Jacob Campbell"
description              : "This site is my home for all of my stuff. I am a school social worker, adjunct faculty member for a university, Ph.D. Student, Licensed Independent Clinical Social Worker, father, husband, and active community member"
url                      : "https://jacobrcampbell.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "campjacob/campjacob.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/src/jacob-campbell-logo.svg"
masthead_title           : " "
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider: "discourse"
  discourse:
    server: talk.jacobrcampbell.com
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : campjacob
facebook:
  username               : jacobshouse
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/campjacob"
    - "https://facebook.com/jacobshouse"
    - "https://instagram.com/campjacob"
    - "https://www.linkedin.com/in/jacobrcampbell/"

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-1083867-2"
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Jacob Campbell"
  avatar           : "/assets/src/jacob-campbell-profile-photo.jpeg"
  bio              : "School social worker practicing with students with EBD, university adjunct faculty, PhD student, Licensed Independent Clinical Social Worker, father, husband, and active community member"
  location         : "Pasco, Washington"
  email            : # "jacob.r.campbell@gmail.com"
  links:
    - label: "Contact Me"
      icon: "fas fa-id-card"
      url: "/contact/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/user/campjacob/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/campjacob"
    - label: "Snapchat"
      icon: "fab fa-snapchat-ghost"
      url: "https://www.snapchat.com/add/campjacob1982"

    

# Site Footer
footer:
  links:
    - label: "Contact Me"
      icon: "fas fa-id-card"
      url: "/contact/"
    - label: ""
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/user/campjacob/"
    - label: ""
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/campjacob"
    - label: ""
      icon: "fab fa-snapchat-ghost"
      url: "https://www.snapchat.com/add/campjacob1982"
    - label: ""
      icon: "fab fa-facebook"
      url: "https://fb.com/jacobshouse"
    - label: ""
      icon: "fab fa-instagram"
      url: "https://instagram.com/campjacob"
    - label: ""
      icon: "fab fa-github"
      url: "https://github.com/campjacob"
    - label: ""
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/jacobrcampbell/"

# Reading Files
include:
  - .htaccess
  - _pages
  - _data
  - _resources
  - _includes
  - _communications
  - _dictionary
  - _microposts

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


collections:
  resources:
    output: true
    permalink: /:collection/:path/

  communications:
    output: true
    permalink: /:collection/:name/

  dictionary:
    output: true
    permalink: /:collection/:path/

  microposts:
    output: true
    permalink: /:collection/:path/

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /blog/:year/:month/:title/
paginate: 8 # amount of posts to show
paginate_path: /blog/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _resources
  - scope:
      path: ""
      type: resources
    values:
      layout: single
      share: true
      toc: true
      toc_label: Table of Contents
      sidebar:
        nav: "resources"
  # _communications
  - scope:
      path: ""
      type: communications
    values:
      layout: communication
      author_profile: true
      share: true
      related: true
  # _dictionary
  - scope:
      path: ""
      type: dictionary
    values:
      term: true
      layout: single-dictionary
      share: true
      author_profile: true
  # _microposts
  - scope:
      path: ""
      type: microposts
    values:
      layout: single
      share: true
      author_profile: true